txt = input('Digite algo: ')
print('Tipo primitivo: {}'.format(type(txt)))
print('Só tem espaços: {}'.format(txt.isspace()))
print('Alfabético: {}'.format(txt.isalpha()))
print('Numérico: {}'.format(txt.isnumeric()))
print('Alfanumérico: {}'.format(txt.isalnum()))
print('Em maiúsculas: {}'.format(txt.isupper()))
print('Em minúsculas: {}'.format(txt.islower()))
print('Está capitalizado: {}'.format(txt.istitle()))