print('{}Desafio 009{}'.format('=' * 5, '=' * 5))
n = int(input('Digite um número: '))
print('{}Tabuada do {}{}'.format('=' * 5, n, '=' * 5))
print('{} x {:2} = {:2}'.format(n, 1, n*1))
print('{} x {:2} = {}'.format(n, 2, n*2))
print('{} x {:2} = {}'.format(n, 3, n*3))
print('{} x {:2} = {}'.format(n, 4, n*4))
print('{} x {:2} = {}'.format(n, 5, n*5))
print('{} x {:2} = {}'.format(n, 6, n*6))
print('{} x {:2} = {}'.format(n, 7, n*7))
print('{} x {:2} = {}'.format(n, 8, n*8))
print('{} x {:2} = {}'.format(n, 9, n*9))
print('{} x 10 = {}'.format(n, n*10))
print('=' * 22)